ruby_on_rails_url: "https://www.railstutorial.org/"
rails_home_url: "http://www.railstutorial.org/"
rails_help_url: "http://www.railstutorial.org/help"
rails_book_url: "http://www.railstutorial.org/book"
rails_contact_url: "https://www.railstutorial.org/contact"
rails_new_url: "https://news.railstutorial.org/"
learn_enough_url: "https://www.learnenough.com/"
author_url: "https://www.michaelhartl.com/"
